apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: nestit
  newName: andrewjpb/nestjs-administration-service-it
  newTag: 8de33fc55249a21f9bc47aafdbf0a526c2d4f313
