apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: nestit
  newName: /nestjs-administration-service-it
  newTag: 8a990d7cca21d10cfe756b252c9dcc00c34bcea2
