name: ci-nestjs-workflow
on:
  push:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.1.0', '19.1.0']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
